### ISSUE TITLE
Visual changes

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-foundation/radworks-docs#246]
- [x] Change background color to `#EBEFF3`
- [x] Change headings to [Terminal Grotesque](https://files.design/templates/terminal-grotesque)
- [x] remove gradient in the header
- [x] remove dashed border around search box
- [x] change background color of search box to white
- [x] Change button border-radii to fully rounded
- [x] change primary button background color to `#53DB53`
- [x] change favicon to standard token logo

And I think if you do those few things, we should be pretty good to go in matching the Radworks website.

**Comment by abbey-titcomb** [comment]
hey @joelhans - do you think you'd be able to help with these?
