### ISSUE TITLE
capitalization is wrong here

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-foundation/radworks-docs#248]
It should be spelled "Radworks"

<img width="401" alt="image" src="https://github.com/radicle-foundation/radicle-docs/assets/4406983/1da52d6b-341f-4110-9289-eab6980dc349">

**Comment by joelhans** [comment]
Fixed in https://github.com/radicle-foundation/radicle-docs/pull/243/commits/e33c932abad7bfad517b1db9b5ba3ea1df0ff6d7
