### ISSUE TITLE
This should say Radworks, not RadicleDAO

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-foundation/radworks-docs#249]
There are two in this paragraph, but I only circled one. Just do a Find & Replace probably.

<img width="846" alt="Screenshot 2023-06-12 at 14 24 08" src="https://github.com/radicle-foundation/radicle-docs/assets/4406983/49aaa2b1-4de0-44b8-b90d-f4ec01670431">

**Comment by joelhans** [comment]
Fixed in https://github.com/radicle-foundation/radicle-docs/pull/243/commits/e33c932abad7bfad517b1db9b5ba3ea1df0ff6d7
